# Use an official Node.js image
FROM node:18

# Set working directory
WORKDIR ../task-management-api

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Expose the port your app runs on
EXPOSE 8000

# Start the application
CMD ["node", "index.js"]
