services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PORT: 8000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: task_management
      JWT_SECRET: supersecret
      JWT_REFRESH_SECRET: superrefreshsecret
      EMAIL_USER: your@email.com
      EMAIL_PASS: emailpassword

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
